// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pdl.proto

package com.the9.common.proto;

public final class Pdl {
  private Pdl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface LoginGame_C2S_MsgOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code com.the9.common.proto.LoginGame_C2S_Msg}
   */
  public static final class LoginGame_C2S_Msg extends
      com.google.protobuf.GeneratedMessage
      implements LoginGame_C2S_MsgOrBuilder {
    // Use LoginGame_C2S_Msg.newBuilder() to construct.
    private LoginGame_C2S_Msg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private LoginGame_C2S_Msg(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final LoginGame_C2S_Msg defaultInstance;
    public static LoginGame_C2S_Msg getDefaultInstance() {
      return defaultInstance;
    }

    public LoginGame_C2S_Msg getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private LoginGame_C2S_Msg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.the9.common.proto.Pdl.internal_static_com_the9_common_proto_LoginGame_C2S_Msg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.the9.common.proto.Pdl.internal_static_com_the9_common_proto_LoginGame_C2S_Msg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.the9.common.proto.Pdl.LoginGame_C2S_Msg.class, com.the9.common.proto.Pdl.LoginGame_C2S_Msg.Builder.class);
    }

    public static com.google.protobuf.Parser<LoginGame_C2S_Msg> PARSER =
        new com.google.protobuf.AbstractParser<LoginGame_C2S_Msg>() {
      public LoginGame_C2S_Msg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LoginGame_C2S_Msg(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<LoginGame_C2S_Msg> getParserForType() {
      return PARSER;
    }

    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.the9.common.proto.Pdl.LoginGame_C2S_Msg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.the9.common.proto.Pdl.LoginGame_C2S_Msg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.the9.common.proto.Pdl.LoginGame_C2S_Msg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.the9.common.proto.Pdl.LoginGame_C2S_Msg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.the9.common.proto.Pdl.LoginGame_C2S_Msg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.the9.common.proto.Pdl.LoginGame_C2S_Msg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.the9.common.proto.Pdl.LoginGame_C2S_Msg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.the9.common.proto.Pdl.LoginGame_C2S_Msg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.the9.common.proto.Pdl.LoginGame_C2S_Msg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.the9.common.proto.Pdl.LoginGame_C2S_Msg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.the9.common.proto.Pdl.LoginGame_C2S_Msg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.the9.common.proto.LoginGame_C2S_Msg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.the9.common.proto.Pdl.LoginGame_C2S_MsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.the9.common.proto.Pdl.internal_static_com_the9_common_proto_LoginGame_C2S_Msg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.the9.common.proto.Pdl.internal_static_com_the9_common_proto_LoginGame_C2S_Msg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.the9.common.proto.Pdl.LoginGame_C2S_Msg.class, com.the9.common.proto.Pdl.LoginGame_C2S_Msg.Builder.class);
      }

      // Construct using com.the9.common.proto.Pdl.LoginGame_C2S_Msg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.the9.common.proto.Pdl.internal_static_com_the9_common_proto_LoginGame_C2S_Msg_descriptor;
      }

      public com.the9.common.proto.Pdl.LoginGame_C2S_Msg getDefaultInstanceForType() {
        return com.the9.common.proto.Pdl.LoginGame_C2S_Msg.getDefaultInstance();
      }

      public com.the9.common.proto.Pdl.LoginGame_C2S_Msg build() {
        com.the9.common.proto.Pdl.LoginGame_C2S_Msg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.the9.common.proto.Pdl.LoginGame_C2S_Msg buildPartial() {
        com.the9.common.proto.Pdl.LoginGame_C2S_Msg result = new com.the9.common.proto.Pdl.LoginGame_C2S_Msg(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.the9.common.proto.Pdl.LoginGame_C2S_Msg) {
          return mergeFrom((com.the9.common.proto.Pdl.LoginGame_C2S_Msg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.the9.common.proto.Pdl.LoginGame_C2S_Msg other) {
        if (other == com.the9.common.proto.Pdl.LoginGame_C2S_Msg.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.the9.common.proto.Pdl.LoginGame_C2S_Msg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.the9.common.proto.Pdl.LoginGame_C2S_Msg) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.the9.common.proto.LoginGame_C2S_Msg)
    }

    static {
      defaultInstance = new LoginGame_C2S_Msg(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.the9.common.proto.LoginGame_C2S_Msg)
  }

  public interface LoginGame_S2C_MsgOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .com.the9.common.proto.UserDTO userDTO = 1;
    /**
     * <code>required .com.the9.common.proto.UserDTO userDTO = 1;</code>
     */
    boolean hasUserDTO();
    /**
     * <code>required .com.the9.common.proto.UserDTO userDTO = 1;</code>
     */
    com.the9.common.proto.Common.UserDTO getUserDTO();
    /**
     * <code>required .com.the9.common.proto.UserDTO userDTO = 1;</code>
     */
    com.the9.common.proto.Common.UserDTOOrBuilder getUserDTOOrBuilder();
  }
  /**
   * Protobuf type {@code com.the9.common.proto.LoginGame_S2C_Msg}
   */
  public static final class LoginGame_S2C_Msg extends
      com.google.protobuf.GeneratedMessage
      implements LoginGame_S2C_MsgOrBuilder {
    // Use LoginGame_S2C_Msg.newBuilder() to construct.
    private LoginGame_S2C_Msg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private LoginGame_S2C_Msg(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final LoginGame_S2C_Msg defaultInstance;
    public static LoginGame_S2C_Msg getDefaultInstance() {
      return defaultInstance;
    }

    public LoginGame_S2C_Msg getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private LoginGame_S2C_Msg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.the9.common.proto.Common.UserDTO.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = userDTO_.toBuilder();
              }
              userDTO_ = input.readMessage(com.the9.common.proto.Common.UserDTO.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(userDTO_);
                userDTO_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.the9.common.proto.Pdl.internal_static_com_the9_common_proto_LoginGame_S2C_Msg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.the9.common.proto.Pdl.internal_static_com_the9_common_proto_LoginGame_S2C_Msg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.the9.common.proto.Pdl.LoginGame_S2C_Msg.class, com.the9.common.proto.Pdl.LoginGame_S2C_Msg.Builder.class);
    }

    public static com.google.protobuf.Parser<LoginGame_S2C_Msg> PARSER =
        new com.google.protobuf.AbstractParser<LoginGame_S2C_Msg>() {
      public LoginGame_S2C_Msg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LoginGame_S2C_Msg(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<LoginGame_S2C_Msg> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required .com.the9.common.proto.UserDTO userDTO = 1;
    public static final int USERDTO_FIELD_NUMBER = 1;
    private com.the9.common.proto.Common.UserDTO userDTO_;
    /**
     * <code>required .com.the9.common.proto.UserDTO userDTO = 1;</code>
     */
    public boolean hasUserDTO() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .com.the9.common.proto.UserDTO userDTO = 1;</code>
     */
    public com.the9.common.proto.Common.UserDTO getUserDTO() {
      return userDTO_;
    }
    /**
     * <code>required .com.the9.common.proto.UserDTO userDTO = 1;</code>
     */
    public com.the9.common.proto.Common.UserDTOOrBuilder getUserDTOOrBuilder() {
      return userDTO_;
    }

    private void initFields() {
      userDTO_ = com.the9.common.proto.Common.UserDTO.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasUserDTO()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getUserDTO().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, userDTO_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, userDTO_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.the9.common.proto.Pdl.LoginGame_S2C_Msg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.the9.common.proto.Pdl.LoginGame_S2C_Msg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.the9.common.proto.Pdl.LoginGame_S2C_Msg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.the9.common.proto.Pdl.LoginGame_S2C_Msg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.the9.common.proto.Pdl.LoginGame_S2C_Msg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.the9.common.proto.Pdl.LoginGame_S2C_Msg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.the9.common.proto.Pdl.LoginGame_S2C_Msg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.the9.common.proto.Pdl.LoginGame_S2C_Msg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.the9.common.proto.Pdl.LoginGame_S2C_Msg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.the9.common.proto.Pdl.LoginGame_S2C_Msg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.the9.common.proto.Pdl.LoginGame_S2C_Msg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.the9.common.proto.LoginGame_S2C_Msg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.the9.common.proto.Pdl.LoginGame_S2C_MsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.the9.common.proto.Pdl.internal_static_com_the9_common_proto_LoginGame_S2C_Msg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.the9.common.proto.Pdl.internal_static_com_the9_common_proto_LoginGame_S2C_Msg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.the9.common.proto.Pdl.LoginGame_S2C_Msg.class, com.the9.common.proto.Pdl.LoginGame_S2C_Msg.Builder.class);
      }

      // Construct using com.the9.common.proto.Pdl.LoginGame_S2C_Msg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getUserDTOFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (userDTOBuilder_ == null) {
          userDTO_ = com.the9.common.proto.Common.UserDTO.getDefaultInstance();
        } else {
          userDTOBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.the9.common.proto.Pdl.internal_static_com_the9_common_proto_LoginGame_S2C_Msg_descriptor;
      }

      public com.the9.common.proto.Pdl.LoginGame_S2C_Msg getDefaultInstanceForType() {
        return com.the9.common.proto.Pdl.LoginGame_S2C_Msg.getDefaultInstance();
      }

      public com.the9.common.proto.Pdl.LoginGame_S2C_Msg build() {
        com.the9.common.proto.Pdl.LoginGame_S2C_Msg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.the9.common.proto.Pdl.LoginGame_S2C_Msg buildPartial() {
        com.the9.common.proto.Pdl.LoginGame_S2C_Msg result = new com.the9.common.proto.Pdl.LoginGame_S2C_Msg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (userDTOBuilder_ == null) {
          result.userDTO_ = userDTO_;
        } else {
          result.userDTO_ = userDTOBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.the9.common.proto.Pdl.LoginGame_S2C_Msg) {
          return mergeFrom((com.the9.common.proto.Pdl.LoginGame_S2C_Msg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.the9.common.proto.Pdl.LoginGame_S2C_Msg other) {
        if (other == com.the9.common.proto.Pdl.LoginGame_S2C_Msg.getDefaultInstance()) return this;
        if (other.hasUserDTO()) {
          mergeUserDTO(other.getUserDTO());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUserDTO()) {
          
          return false;
        }
        if (!getUserDTO().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.the9.common.proto.Pdl.LoginGame_S2C_Msg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.the9.common.proto.Pdl.LoginGame_S2C_Msg) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .com.the9.common.proto.UserDTO userDTO = 1;
      private com.the9.common.proto.Common.UserDTO userDTO_ = com.the9.common.proto.Common.UserDTO.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.the9.common.proto.Common.UserDTO, com.the9.common.proto.Common.UserDTO.Builder, com.the9.common.proto.Common.UserDTOOrBuilder> userDTOBuilder_;
      /**
       * <code>required .com.the9.common.proto.UserDTO userDTO = 1;</code>
       */
      public boolean hasUserDTO() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .com.the9.common.proto.UserDTO userDTO = 1;</code>
       */
      public com.the9.common.proto.Common.UserDTO getUserDTO() {
        if (userDTOBuilder_ == null) {
          return userDTO_;
        } else {
          return userDTOBuilder_.getMessage();
        }
      }
      /**
       * <code>required .com.the9.common.proto.UserDTO userDTO = 1;</code>
       */
      public Builder setUserDTO(com.the9.common.proto.Common.UserDTO value) {
        if (userDTOBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          userDTO_ = value;
          onChanged();
        } else {
          userDTOBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .com.the9.common.proto.UserDTO userDTO = 1;</code>
       */
      public Builder setUserDTO(
          com.the9.common.proto.Common.UserDTO.Builder builderForValue) {
        if (userDTOBuilder_ == null) {
          userDTO_ = builderForValue.build();
          onChanged();
        } else {
          userDTOBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .com.the9.common.proto.UserDTO userDTO = 1;</code>
       */
      public Builder mergeUserDTO(com.the9.common.proto.Common.UserDTO value) {
        if (userDTOBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              userDTO_ != com.the9.common.proto.Common.UserDTO.getDefaultInstance()) {
            userDTO_ =
              com.the9.common.proto.Common.UserDTO.newBuilder(userDTO_).mergeFrom(value).buildPartial();
          } else {
            userDTO_ = value;
          }
          onChanged();
        } else {
          userDTOBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .com.the9.common.proto.UserDTO userDTO = 1;</code>
       */
      public Builder clearUserDTO() {
        if (userDTOBuilder_ == null) {
          userDTO_ = com.the9.common.proto.Common.UserDTO.getDefaultInstance();
          onChanged();
        } else {
          userDTOBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>required .com.the9.common.proto.UserDTO userDTO = 1;</code>
       */
      public com.the9.common.proto.Common.UserDTO.Builder getUserDTOBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getUserDTOFieldBuilder().getBuilder();
      }
      /**
       * <code>required .com.the9.common.proto.UserDTO userDTO = 1;</code>
       */
      public com.the9.common.proto.Common.UserDTOOrBuilder getUserDTOOrBuilder() {
        if (userDTOBuilder_ != null) {
          return userDTOBuilder_.getMessageOrBuilder();
        } else {
          return userDTO_;
        }
      }
      /**
       * <code>required .com.the9.common.proto.UserDTO userDTO = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.the9.common.proto.Common.UserDTO, com.the9.common.proto.Common.UserDTO.Builder, com.the9.common.proto.Common.UserDTOOrBuilder> 
          getUserDTOFieldBuilder() {
        if (userDTOBuilder_ == null) {
          userDTOBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.the9.common.proto.Common.UserDTO, com.the9.common.proto.Common.UserDTO.Builder, com.the9.common.proto.Common.UserDTOOrBuilder>(
                  userDTO_,
                  getParentForChildren(),
                  isClean());
          userDTO_ = null;
        }
        return userDTOBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.the9.common.proto.LoginGame_S2C_Msg)
    }

    static {
      defaultInstance = new LoginGame_S2C_Msg(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.the9.common.proto.LoginGame_S2C_Msg)
  }

  public interface LoginOut_C2S_MsgOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 userId = 1;
    /**
     * <code>required int32 userId = 1;</code>
     */
    boolean hasUserId();
    /**
     * <code>required int32 userId = 1;</code>
     */
    int getUserId();
  }
  /**
   * Protobuf type {@code com.the9.common.proto.LoginOut_C2S_Msg}
   */
  public static final class LoginOut_C2S_Msg extends
      com.google.protobuf.GeneratedMessage
      implements LoginOut_C2S_MsgOrBuilder {
    // Use LoginOut_C2S_Msg.newBuilder() to construct.
    private LoginOut_C2S_Msg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private LoginOut_C2S_Msg(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final LoginOut_C2S_Msg defaultInstance;
    public static LoginOut_C2S_Msg getDefaultInstance() {
      return defaultInstance;
    }

    public LoginOut_C2S_Msg getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private LoginOut_C2S_Msg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              userId_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.the9.common.proto.Pdl.internal_static_com_the9_common_proto_LoginOut_C2S_Msg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.the9.common.proto.Pdl.internal_static_com_the9_common_proto_LoginOut_C2S_Msg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.the9.common.proto.Pdl.LoginOut_C2S_Msg.class, com.the9.common.proto.Pdl.LoginOut_C2S_Msg.Builder.class);
    }

    public static com.google.protobuf.Parser<LoginOut_C2S_Msg> PARSER =
        new com.google.protobuf.AbstractParser<LoginOut_C2S_Msg>() {
      public LoginOut_C2S_Msg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LoginOut_C2S_Msg(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<LoginOut_C2S_Msg> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 userId = 1;
    public static final int USERID_FIELD_NUMBER = 1;
    private int userId_;
    /**
     * <code>required int32 userId = 1;</code>
     */
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 userId = 1;</code>
     */
    public int getUserId() {
      return userId_;
    }

    private void initFields() {
      userId_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasUserId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, userId_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, userId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.the9.common.proto.Pdl.LoginOut_C2S_Msg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.the9.common.proto.Pdl.LoginOut_C2S_Msg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.the9.common.proto.Pdl.LoginOut_C2S_Msg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.the9.common.proto.Pdl.LoginOut_C2S_Msg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.the9.common.proto.Pdl.LoginOut_C2S_Msg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.the9.common.proto.Pdl.LoginOut_C2S_Msg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.the9.common.proto.Pdl.LoginOut_C2S_Msg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.the9.common.proto.Pdl.LoginOut_C2S_Msg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.the9.common.proto.Pdl.LoginOut_C2S_Msg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.the9.common.proto.Pdl.LoginOut_C2S_Msg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.the9.common.proto.Pdl.LoginOut_C2S_Msg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.the9.common.proto.LoginOut_C2S_Msg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.the9.common.proto.Pdl.LoginOut_C2S_MsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.the9.common.proto.Pdl.internal_static_com_the9_common_proto_LoginOut_C2S_Msg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.the9.common.proto.Pdl.internal_static_com_the9_common_proto_LoginOut_C2S_Msg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.the9.common.proto.Pdl.LoginOut_C2S_Msg.class, com.the9.common.proto.Pdl.LoginOut_C2S_Msg.Builder.class);
      }

      // Construct using com.the9.common.proto.Pdl.LoginOut_C2S_Msg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        userId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.the9.common.proto.Pdl.internal_static_com_the9_common_proto_LoginOut_C2S_Msg_descriptor;
      }

      public com.the9.common.proto.Pdl.LoginOut_C2S_Msg getDefaultInstanceForType() {
        return com.the9.common.proto.Pdl.LoginOut_C2S_Msg.getDefaultInstance();
      }

      public com.the9.common.proto.Pdl.LoginOut_C2S_Msg build() {
        com.the9.common.proto.Pdl.LoginOut_C2S_Msg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.the9.common.proto.Pdl.LoginOut_C2S_Msg buildPartial() {
        com.the9.common.proto.Pdl.LoginOut_C2S_Msg result = new com.the9.common.proto.Pdl.LoginOut_C2S_Msg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.userId_ = userId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.the9.common.proto.Pdl.LoginOut_C2S_Msg) {
          return mergeFrom((com.the9.common.proto.Pdl.LoginOut_C2S_Msg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.the9.common.proto.Pdl.LoginOut_C2S_Msg other) {
        if (other == com.the9.common.proto.Pdl.LoginOut_C2S_Msg.getDefaultInstance()) return this;
        if (other.hasUserId()) {
          setUserId(other.getUserId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUserId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.the9.common.proto.Pdl.LoginOut_C2S_Msg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.the9.common.proto.Pdl.LoginOut_C2S_Msg) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 userId = 1;
      private int userId_ ;
      /**
       * <code>required int32 userId = 1;</code>
       */
      public boolean hasUserId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 userId = 1;</code>
       */
      public int getUserId() {
        return userId_;
      }
      /**
       * <code>required int32 userId = 1;</code>
       */
      public Builder setUserId(int value) {
        bitField0_ |= 0x00000001;
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 userId = 1;</code>
       */
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        userId_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.the9.common.proto.LoginOut_C2S_Msg)
    }

    static {
      defaultInstance = new LoginOut_C2S_Msg(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.the9.common.proto.LoginOut_C2S_Msg)
  }

  public interface MaintainNotice_S2C_MsgOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string content = 1;
    /**
     * <code>required string content = 1;</code>
     */
    boolean hasContent();
    /**
     * <code>required string content = 1;</code>
     */
    java.lang.String getContent();
    /**
     * <code>required string content = 1;</code>
     */
    com.google.protobuf.ByteString
        getContentBytes();
  }
  /**
   * Protobuf type {@code com.the9.common.proto.MaintainNotice_S2C_Msg}
   */
  public static final class MaintainNotice_S2C_Msg extends
      com.google.protobuf.GeneratedMessage
      implements MaintainNotice_S2C_MsgOrBuilder {
    // Use MaintainNotice_S2C_Msg.newBuilder() to construct.
    private MaintainNotice_S2C_Msg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MaintainNotice_S2C_Msg(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MaintainNotice_S2C_Msg defaultInstance;
    public static MaintainNotice_S2C_Msg getDefaultInstance() {
      return defaultInstance;
    }

    public MaintainNotice_S2C_Msg getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private MaintainNotice_S2C_Msg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              content_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.the9.common.proto.Pdl.internal_static_com_the9_common_proto_MaintainNotice_S2C_Msg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.the9.common.proto.Pdl.internal_static_com_the9_common_proto_MaintainNotice_S2C_Msg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.the9.common.proto.Pdl.MaintainNotice_S2C_Msg.class, com.the9.common.proto.Pdl.MaintainNotice_S2C_Msg.Builder.class);
    }

    public static com.google.protobuf.Parser<MaintainNotice_S2C_Msg> PARSER =
        new com.google.protobuf.AbstractParser<MaintainNotice_S2C_Msg>() {
      public MaintainNotice_S2C_Msg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MaintainNotice_S2C_Msg(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MaintainNotice_S2C_Msg> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string content = 1;
    public static final int CONTENT_FIELD_NUMBER = 1;
    private java.lang.Object content_;
    /**
     * <code>required string content = 1;</code>
     */
    public boolean hasContent() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string content = 1;</code>
     */
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          content_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string content = 1;</code>
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      content_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasContent()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getContentBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getContentBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.the9.common.proto.Pdl.MaintainNotice_S2C_Msg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.the9.common.proto.Pdl.MaintainNotice_S2C_Msg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.the9.common.proto.Pdl.MaintainNotice_S2C_Msg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.the9.common.proto.Pdl.MaintainNotice_S2C_Msg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.the9.common.proto.Pdl.MaintainNotice_S2C_Msg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.the9.common.proto.Pdl.MaintainNotice_S2C_Msg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.the9.common.proto.Pdl.MaintainNotice_S2C_Msg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.the9.common.proto.Pdl.MaintainNotice_S2C_Msg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.the9.common.proto.Pdl.MaintainNotice_S2C_Msg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.the9.common.proto.Pdl.MaintainNotice_S2C_Msg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.the9.common.proto.Pdl.MaintainNotice_S2C_Msg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.the9.common.proto.MaintainNotice_S2C_Msg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.the9.common.proto.Pdl.MaintainNotice_S2C_MsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.the9.common.proto.Pdl.internal_static_com_the9_common_proto_MaintainNotice_S2C_Msg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.the9.common.proto.Pdl.internal_static_com_the9_common_proto_MaintainNotice_S2C_Msg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.the9.common.proto.Pdl.MaintainNotice_S2C_Msg.class, com.the9.common.proto.Pdl.MaintainNotice_S2C_Msg.Builder.class);
      }

      // Construct using com.the9.common.proto.Pdl.MaintainNotice_S2C_Msg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        content_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.the9.common.proto.Pdl.internal_static_com_the9_common_proto_MaintainNotice_S2C_Msg_descriptor;
      }

      public com.the9.common.proto.Pdl.MaintainNotice_S2C_Msg getDefaultInstanceForType() {
        return com.the9.common.proto.Pdl.MaintainNotice_S2C_Msg.getDefaultInstance();
      }

      public com.the9.common.proto.Pdl.MaintainNotice_S2C_Msg build() {
        com.the9.common.proto.Pdl.MaintainNotice_S2C_Msg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.the9.common.proto.Pdl.MaintainNotice_S2C_Msg buildPartial() {
        com.the9.common.proto.Pdl.MaintainNotice_S2C_Msg result = new com.the9.common.proto.Pdl.MaintainNotice_S2C_Msg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.content_ = content_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.the9.common.proto.Pdl.MaintainNotice_S2C_Msg) {
          return mergeFrom((com.the9.common.proto.Pdl.MaintainNotice_S2C_Msg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.the9.common.proto.Pdl.MaintainNotice_S2C_Msg other) {
        if (other == com.the9.common.proto.Pdl.MaintainNotice_S2C_Msg.getDefaultInstance()) return this;
        if (other.hasContent()) {
          bitField0_ |= 0x00000001;
          content_ = other.content_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasContent()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.the9.common.proto.Pdl.MaintainNotice_S2C_Msg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.the9.common.proto.Pdl.MaintainNotice_S2C_Msg) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string content = 1;
      private java.lang.Object content_ = "";
      /**
       * <code>required string content = 1;</code>
       */
      public boolean hasContent() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string content = 1;</code>
       */
      public java.lang.String getContent() {
        java.lang.Object ref = content_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string content = 1;</code>
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        java.lang.Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string content = 1;</code>
       */
      public Builder setContent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string content = 1;</code>
       */
      public Builder clearContent() {
        bitField0_ = (bitField0_ & ~0x00000001);
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      /**
       * <code>required string content = 1;</code>
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        content_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.the9.common.proto.MaintainNotice_S2C_Msg)
    }

    static {
      defaultInstance = new MaintainNotice_S2C_Msg(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.the9.common.proto.MaintainNotice_S2C_Msg)
  }

  public interface KeepAlive_C2S_MsgOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code com.the9.common.proto.KeepAlive_C2S_Msg}
   */
  public static final class KeepAlive_C2S_Msg extends
      com.google.protobuf.GeneratedMessage
      implements KeepAlive_C2S_MsgOrBuilder {
    // Use KeepAlive_C2S_Msg.newBuilder() to construct.
    private KeepAlive_C2S_Msg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private KeepAlive_C2S_Msg(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final KeepAlive_C2S_Msg defaultInstance;
    public static KeepAlive_C2S_Msg getDefaultInstance() {
      return defaultInstance;
    }

    public KeepAlive_C2S_Msg getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private KeepAlive_C2S_Msg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.the9.common.proto.Pdl.internal_static_com_the9_common_proto_KeepAlive_C2S_Msg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.the9.common.proto.Pdl.internal_static_com_the9_common_proto_KeepAlive_C2S_Msg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.the9.common.proto.Pdl.KeepAlive_C2S_Msg.class, com.the9.common.proto.Pdl.KeepAlive_C2S_Msg.Builder.class);
    }

    public static com.google.protobuf.Parser<KeepAlive_C2S_Msg> PARSER =
        new com.google.protobuf.AbstractParser<KeepAlive_C2S_Msg>() {
      public KeepAlive_C2S_Msg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new KeepAlive_C2S_Msg(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<KeepAlive_C2S_Msg> getParserForType() {
      return PARSER;
    }

    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.the9.common.proto.Pdl.KeepAlive_C2S_Msg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.the9.common.proto.Pdl.KeepAlive_C2S_Msg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.the9.common.proto.Pdl.KeepAlive_C2S_Msg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.the9.common.proto.Pdl.KeepAlive_C2S_Msg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.the9.common.proto.Pdl.KeepAlive_C2S_Msg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.the9.common.proto.Pdl.KeepAlive_C2S_Msg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.the9.common.proto.Pdl.KeepAlive_C2S_Msg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.the9.common.proto.Pdl.KeepAlive_C2S_Msg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.the9.common.proto.Pdl.KeepAlive_C2S_Msg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.the9.common.proto.Pdl.KeepAlive_C2S_Msg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.the9.common.proto.Pdl.KeepAlive_C2S_Msg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.the9.common.proto.KeepAlive_C2S_Msg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.the9.common.proto.Pdl.KeepAlive_C2S_MsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.the9.common.proto.Pdl.internal_static_com_the9_common_proto_KeepAlive_C2S_Msg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.the9.common.proto.Pdl.internal_static_com_the9_common_proto_KeepAlive_C2S_Msg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.the9.common.proto.Pdl.KeepAlive_C2S_Msg.class, com.the9.common.proto.Pdl.KeepAlive_C2S_Msg.Builder.class);
      }

      // Construct using com.the9.common.proto.Pdl.KeepAlive_C2S_Msg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.the9.common.proto.Pdl.internal_static_com_the9_common_proto_KeepAlive_C2S_Msg_descriptor;
      }

      public com.the9.common.proto.Pdl.KeepAlive_C2S_Msg getDefaultInstanceForType() {
        return com.the9.common.proto.Pdl.KeepAlive_C2S_Msg.getDefaultInstance();
      }

      public com.the9.common.proto.Pdl.KeepAlive_C2S_Msg build() {
        com.the9.common.proto.Pdl.KeepAlive_C2S_Msg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.the9.common.proto.Pdl.KeepAlive_C2S_Msg buildPartial() {
        com.the9.common.proto.Pdl.KeepAlive_C2S_Msg result = new com.the9.common.proto.Pdl.KeepAlive_C2S_Msg(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.the9.common.proto.Pdl.KeepAlive_C2S_Msg) {
          return mergeFrom((com.the9.common.proto.Pdl.KeepAlive_C2S_Msg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.the9.common.proto.Pdl.KeepAlive_C2S_Msg other) {
        if (other == com.the9.common.proto.Pdl.KeepAlive_C2S_Msg.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.the9.common.proto.Pdl.KeepAlive_C2S_Msg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.the9.common.proto.Pdl.KeepAlive_C2S_Msg) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.the9.common.proto.KeepAlive_C2S_Msg)
    }

    static {
      defaultInstance = new KeepAlive_C2S_Msg(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.the9.common.proto.KeepAlive_C2S_Msg)
  }

  public interface KeepAlive_S2C_MsgOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code com.the9.common.proto.KeepAlive_S2C_Msg}
   */
  public static final class KeepAlive_S2C_Msg extends
      com.google.protobuf.GeneratedMessage
      implements KeepAlive_S2C_MsgOrBuilder {
    // Use KeepAlive_S2C_Msg.newBuilder() to construct.
    private KeepAlive_S2C_Msg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private KeepAlive_S2C_Msg(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final KeepAlive_S2C_Msg defaultInstance;
    public static KeepAlive_S2C_Msg getDefaultInstance() {
      return defaultInstance;
    }

    public KeepAlive_S2C_Msg getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private KeepAlive_S2C_Msg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.the9.common.proto.Pdl.internal_static_com_the9_common_proto_KeepAlive_S2C_Msg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.the9.common.proto.Pdl.internal_static_com_the9_common_proto_KeepAlive_S2C_Msg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.the9.common.proto.Pdl.KeepAlive_S2C_Msg.class, com.the9.common.proto.Pdl.KeepAlive_S2C_Msg.Builder.class);
    }

    public static com.google.protobuf.Parser<KeepAlive_S2C_Msg> PARSER =
        new com.google.protobuf.AbstractParser<KeepAlive_S2C_Msg>() {
      public KeepAlive_S2C_Msg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new KeepAlive_S2C_Msg(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<KeepAlive_S2C_Msg> getParserForType() {
      return PARSER;
    }

    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.the9.common.proto.Pdl.KeepAlive_S2C_Msg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.the9.common.proto.Pdl.KeepAlive_S2C_Msg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.the9.common.proto.Pdl.KeepAlive_S2C_Msg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.the9.common.proto.Pdl.KeepAlive_S2C_Msg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.the9.common.proto.Pdl.KeepAlive_S2C_Msg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.the9.common.proto.Pdl.KeepAlive_S2C_Msg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.the9.common.proto.Pdl.KeepAlive_S2C_Msg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.the9.common.proto.Pdl.KeepAlive_S2C_Msg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.the9.common.proto.Pdl.KeepAlive_S2C_Msg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.the9.common.proto.Pdl.KeepAlive_S2C_Msg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.the9.common.proto.Pdl.KeepAlive_S2C_Msg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.the9.common.proto.KeepAlive_S2C_Msg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.the9.common.proto.Pdl.KeepAlive_S2C_MsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.the9.common.proto.Pdl.internal_static_com_the9_common_proto_KeepAlive_S2C_Msg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.the9.common.proto.Pdl.internal_static_com_the9_common_proto_KeepAlive_S2C_Msg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.the9.common.proto.Pdl.KeepAlive_S2C_Msg.class, com.the9.common.proto.Pdl.KeepAlive_S2C_Msg.Builder.class);
      }

      // Construct using com.the9.common.proto.Pdl.KeepAlive_S2C_Msg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.the9.common.proto.Pdl.internal_static_com_the9_common_proto_KeepAlive_S2C_Msg_descriptor;
      }

      public com.the9.common.proto.Pdl.KeepAlive_S2C_Msg getDefaultInstanceForType() {
        return com.the9.common.proto.Pdl.KeepAlive_S2C_Msg.getDefaultInstance();
      }

      public com.the9.common.proto.Pdl.KeepAlive_S2C_Msg build() {
        com.the9.common.proto.Pdl.KeepAlive_S2C_Msg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.the9.common.proto.Pdl.KeepAlive_S2C_Msg buildPartial() {
        com.the9.common.proto.Pdl.KeepAlive_S2C_Msg result = new com.the9.common.proto.Pdl.KeepAlive_S2C_Msg(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.the9.common.proto.Pdl.KeepAlive_S2C_Msg) {
          return mergeFrom((com.the9.common.proto.Pdl.KeepAlive_S2C_Msg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.the9.common.proto.Pdl.KeepAlive_S2C_Msg other) {
        if (other == com.the9.common.proto.Pdl.KeepAlive_S2C_Msg.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.the9.common.proto.Pdl.KeepAlive_S2C_Msg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.the9.common.proto.Pdl.KeepAlive_S2C_Msg) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.the9.common.proto.KeepAlive_S2C_Msg)
    }

    static {
      defaultInstance = new KeepAlive_S2C_Msg(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.the9.common.proto.KeepAlive_S2C_Msg)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_the9_common_proto_LoginGame_C2S_Msg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_the9_common_proto_LoginGame_C2S_Msg_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_the9_common_proto_LoginGame_S2C_Msg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_the9_common_proto_LoginGame_S2C_Msg_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_the9_common_proto_LoginOut_C2S_Msg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_the9_common_proto_LoginOut_C2S_Msg_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_the9_common_proto_MaintainNotice_S2C_Msg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_the9_common_proto_MaintainNotice_S2C_Msg_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_the9_common_proto_KeepAlive_C2S_Msg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_the9_common_proto_KeepAlive_C2S_Msg_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_the9_common_proto_KeepAlive_S2C_Msg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_the9_common_proto_KeepAlive_S2C_Msg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tpdl.proto\022\025com.the9.common.proto\032\014comm" +
      "on.proto\"\023\n\021LoginGame_C2S_Msg\"D\n\021LoginGa" +
      "me_S2C_Msg\022/\n\007userDTO\030\001 \002(\0132\036.com.the9.c" +
      "ommon.proto.UserDTO\"\"\n\020LoginOut_C2S_Msg\022" +
      "\016\n\006userId\030\001 \002(\005\")\n\026MaintainNotice_S2C_Ms" +
      "g\022\017\n\007content\030\001 \002(\t\"\023\n\021KeepAlive_C2S_Msg\"" +
      "\023\n\021KeepAlive_S2C_Msg"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_the9_common_proto_LoginGame_C2S_Msg_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_the9_common_proto_LoginGame_C2S_Msg_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_the9_common_proto_LoginGame_C2S_Msg_descriptor,
              new java.lang.String[] { });
          internal_static_com_the9_common_proto_LoginGame_S2C_Msg_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_the9_common_proto_LoginGame_S2C_Msg_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_the9_common_proto_LoginGame_S2C_Msg_descriptor,
              new java.lang.String[] { "UserDTO", });
          internal_static_com_the9_common_proto_LoginOut_C2S_Msg_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_com_the9_common_proto_LoginOut_C2S_Msg_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_the9_common_proto_LoginOut_C2S_Msg_descriptor,
              new java.lang.String[] { "UserId", });
          internal_static_com_the9_common_proto_MaintainNotice_S2C_Msg_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_com_the9_common_proto_MaintainNotice_S2C_Msg_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_the9_common_proto_MaintainNotice_S2C_Msg_descriptor,
              new java.lang.String[] { "Content", });
          internal_static_com_the9_common_proto_KeepAlive_C2S_Msg_descriptor =
            getDescriptor().getMessageTypes().get(4);
          internal_static_com_the9_common_proto_KeepAlive_C2S_Msg_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_the9_common_proto_KeepAlive_C2S_Msg_descriptor,
              new java.lang.String[] { });
          internal_static_com_the9_common_proto_KeepAlive_S2C_Msg_descriptor =
            getDescriptor().getMessageTypes().get(5);
          internal_static_com_the9_common_proto_KeepAlive_S2C_Msg_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_the9_common_proto_KeepAlive_S2C_Msg_descriptor,
              new java.lang.String[] { });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.the9.common.proto.Common.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
