// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

package com.the9.common.proto;

public final class Rpc {
  private Rpc() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface LoginGameReqOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code com.the9.common.proto.LoginGameReq}
   */
  public static final class LoginGameReq extends
      com.google.protobuf.GeneratedMessage
      implements LoginGameReqOrBuilder {
    // Use LoginGameReq.newBuilder() to construct.
    private LoginGameReq(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private LoginGameReq(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final LoginGameReq defaultInstance;
    public static LoginGameReq getDefaultInstance() {
      return defaultInstance;
    }

    public LoginGameReq getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private LoginGameReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.the9.common.proto.Rpc.internal_static_com_the9_common_proto_LoginGameReq_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.the9.common.proto.Rpc.internal_static_com_the9_common_proto_LoginGameReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.the9.common.proto.Rpc.LoginGameReq.class, com.the9.common.proto.Rpc.LoginGameReq.Builder.class);
    }

    public static com.google.protobuf.Parser<LoginGameReq> PARSER =
        new com.google.protobuf.AbstractParser<LoginGameReq>() {
      public LoginGameReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LoginGameReq(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<LoginGameReq> getParserForType() {
      return PARSER;
    }

    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.the9.common.proto.Rpc.LoginGameReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.the9.common.proto.Rpc.LoginGameReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.the9.common.proto.Rpc.LoginGameReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.the9.common.proto.Rpc.LoginGameReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.the9.common.proto.Rpc.LoginGameReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.the9.common.proto.Rpc.LoginGameReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.the9.common.proto.Rpc.LoginGameReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.the9.common.proto.Rpc.LoginGameReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.the9.common.proto.Rpc.LoginGameReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.the9.common.proto.Rpc.LoginGameReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.the9.common.proto.Rpc.LoginGameReq prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.the9.common.proto.LoginGameReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.the9.common.proto.Rpc.LoginGameReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.the9.common.proto.Rpc.internal_static_com_the9_common_proto_LoginGameReq_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.the9.common.proto.Rpc.internal_static_com_the9_common_proto_LoginGameReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.the9.common.proto.Rpc.LoginGameReq.class, com.the9.common.proto.Rpc.LoginGameReq.Builder.class);
      }

      // Construct using com.the9.common.proto.Rpc.LoginGameReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.the9.common.proto.Rpc.internal_static_com_the9_common_proto_LoginGameReq_descriptor;
      }

      public com.the9.common.proto.Rpc.LoginGameReq getDefaultInstanceForType() {
        return com.the9.common.proto.Rpc.LoginGameReq.getDefaultInstance();
      }

      public com.the9.common.proto.Rpc.LoginGameReq build() {
        com.the9.common.proto.Rpc.LoginGameReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.the9.common.proto.Rpc.LoginGameReq buildPartial() {
        com.the9.common.proto.Rpc.LoginGameReq result = new com.the9.common.proto.Rpc.LoginGameReq(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.the9.common.proto.Rpc.LoginGameReq) {
          return mergeFrom((com.the9.common.proto.Rpc.LoginGameReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.the9.common.proto.Rpc.LoginGameReq other) {
        if (other == com.the9.common.proto.Rpc.LoginGameReq.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.the9.common.proto.Rpc.LoginGameReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.the9.common.proto.Rpc.LoginGameReq) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.the9.common.proto.LoginGameReq)
    }

    static {
      defaultInstance = new LoginGameReq(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.the9.common.proto.LoginGameReq)
  }

  public interface LoginGameAckOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .com.the9.common.proto.UserDTO userDTO = 1;
    /**
     * <code>required .com.the9.common.proto.UserDTO userDTO = 1;</code>
     */
    boolean hasUserDTO();
    /**
     * <code>required .com.the9.common.proto.UserDTO userDTO = 1;</code>
     */
    com.the9.common.proto.Common.UserDTO getUserDTO();
    /**
     * <code>required .com.the9.common.proto.UserDTO userDTO = 1;</code>
     */
    com.the9.common.proto.Common.UserDTOOrBuilder getUserDTOOrBuilder();
  }
  /**
   * Protobuf type {@code com.the9.common.proto.LoginGameAck}
   */
  public static final class LoginGameAck extends
      com.google.protobuf.GeneratedMessage
      implements LoginGameAckOrBuilder {
    // Use LoginGameAck.newBuilder() to construct.
    private LoginGameAck(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private LoginGameAck(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final LoginGameAck defaultInstance;
    public static LoginGameAck getDefaultInstance() {
      return defaultInstance;
    }

    public LoginGameAck getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private LoginGameAck(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.the9.common.proto.Common.UserDTO.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = userDTO_.toBuilder();
              }
              userDTO_ = input.readMessage(com.the9.common.proto.Common.UserDTO.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(userDTO_);
                userDTO_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.the9.common.proto.Rpc.internal_static_com_the9_common_proto_LoginGameAck_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.the9.common.proto.Rpc.internal_static_com_the9_common_proto_LoginGameAck_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.the9.common.proto.Rpc.LoginGameAck.class, com.the9.common.proto.Rpc.LoginGameAck.Builder.class);
    }

    public static com.google.protobuf.Parser<LoginGameAck> PARSER =
        new com.google.protobuf.AbstractParser<LoginGameAck>() {
      public LoginGameAck parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LoginGameAck(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<LoginGameAck> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required .com.the9.common.proto.UserDTO userDTO = 1;
    public static final int USERDTO_FIELD_NUMBER = 1;
    private com.the9.common.proto.Common.UserDTO userDTO_;
    /**
     * <code>required .com.the9.common.proto.UserDTO userDTO = 1;</code>
     */
    public boolean hasUserDTO() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .com.the9.common.proto.UserDTO userDTO = 1;</code>
     */
    public com.the9.common.proto.Common.UserDTO getUserDTO() {
      return userDTO_;
    }
    /**
     * <code>required .com.the9.common.proto.UserDTO userDTO = 1;</code>
     */
    public com.the9.common.proto.Common.UserDTOOrBuilder getUserDTOOrBuilder() {
      return userDTO_;
    }

    private void initFields() {
      userDTO_ = com.the9.common.proto.Common.UserDTO.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasUserDTO()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getUserDTO().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, userDTO_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, userDTO_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.the9.common.proto.Rpc.LoginGameAck parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.the9.common.proto.Rpc.LoginGameAck parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.the9.common.proto.Rpc.LoginGameAck parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.the9.common.proto.Rpc.LoginGameAck parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.the9.common.proto.Rpc.LoginGameAck parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.the9.common.proto.Rpc.LoginGameAck parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.the9.common.proto.Rpc.LoginGameAck parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.the9.common.proto.Rpc.LoginGameAck parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.the9.common.proto.Rpc.LoginGameAck parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.the9.common.proto.Rpc.LoginGameAck parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.the9.common.proto.Rpc.LoginGameAck prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.the9.common.proto.LoginGameAck}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.the9.common.proto.Rpc.LoginGameAckOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.the9.common.proto.Rpc.internal_static_com_the9_common_proto_LoginGameAck_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.the9.common.proto.Rpc.internal_static_com_the9_common_proto_LoginGameAck_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.the9.common.proto.Rpc.LoginGameAck.class, com.the9.common.proto.Rpc.LoginGameAck.Builder.class);
      }

      // Construct using com.the9.common.proto.Rpc.LoginGameAck.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getUserDTOFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (userDTOBuilder_ == null) {
          userDTO_ = com.the9.common.proto.Common.UserDTO.getDefaultInstance();
        } else {
          userDTOBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.the9.common.proto.Rpc.internal_static_com_the9_common_proto_LoginGameAck_descriptor;
      }

      public com.the9.common.proto.Rpc.LoginGameAck getDefaultInstanceForType() {
        return com.the9.common.proto.Rpc.LoginGameAck.getDefaultInstance();
      }

      public com.the9.common.proto.Rpc.LoginGameAck build() {
        com.the9.common.proto.Rpc.LoginGameAck result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.the9.common.proto.Rpc.LoginGameAck buildPartial() {
        com.the9.common.proto.Rpc.LoginGameAck result = new com.the9.common.proto.Rpc.LoginGameAck(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (userDTOBuilder_ == null) {
          result.userDTO_ = userDTO_;
        } else {
          result.userDTO_ = userDTOBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.the9.common.proto.Rpc.LoginGameAck) {
          return mergeFrom((com.the9.common.proto.Rpc.LoginGameAck)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.the9.common.proto.Rpc.LoginGameAck other) {
        if (other == com.the9.common.proto.Rpc.LoginGameAck.getDefaultInstance()) return this;
        if (other.hasUserDTO()) {
          mergeUserDTO(other.getUserDTO());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUserDTO()) {
          
          return false;
        }
        if (!getUserDTO().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.the9.common.proto.Rpc.LoginGameAck parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.the9.common.proto.Rpc.LoginGameAck) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .com.the9.common.proto.UserDTO userDTO = 1;
      private com.the9.common.proto.Common.UserDTO userDTO_ = com.the9.common.proto.Common.UserDTO.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.the9.common.proto.Common.UserDTO, com.the9.common.proto.Common.UserDTO.Builder, com.the9.common.proto.Common.UserDTOOrBuilder> userDTOBuilder_;
      /**
       * <code>required .com.the9.common.proto.UserDTO userDTO = 1;</code>
       */
      public boolean hasUserDTO() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .com.the9.common.proto.UserDTO userDTO = 1;</code>
       */
      public com.the9.common.proto.Common.UserDTO getUserDTO() {
        if (userDTOBuilder_ == null) {
          return userDTO_;
        } else {
          return userDTOBuilder_.getMessage();
        }
      }
      /**
       * <code>required .com.the9.common.proto.UserDTO userDTO = 1;</code>
       */
      public Builder setUserDTO(com.the9.common.proto.Common.UserDTO value) {
        if (userDTOBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          userDTO_ = value;
          onChanged();
        } else {
          userDTOBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .com.the9.common.proto.UserDTO userDTO = 1;</code>
       */
      public Builder setUserDTO(
          com.the9.common.proto.Common.UserDTO.Builder builderForValue) {
        if (userDTOBuilder_ == null) {
          userDTO_ = builderForValue.build();
          onChanged();
        } else {
          userDTOBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .com.the9.common.proto.UserDTO userDTO = 1;</code>
       */
      public Builder mergeUserDTO(com.the9.common.proto.Common.UserDTO value) {
        if (userDTOBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              userDTO_ != com.the9.common.proto.Common.UserDTO.getDefaultInstance()) {
            userDTO_ =
              com.the9.common.proto.Common.UserDTO.newBuilder(userDTO_).mergeFrom(value).buildPartial();
          } else {
            userDTO_ = value;
          }
          onChanged();
        } else {
          userDTOBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .com.the9.common.proto.UserDTO userDTO = 1;</code>
       */
      public Builder clearUserDTO() {
        if (userDTOBuilder_ == null) {
          userDTO_ = com.the9.common.proto.Common.UserDTO.getDefaultInstance();
          onChanged();
        } else {
          userDTOBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>required .com.the9.common.proto.UserDTO userDTO = 1;</code>
       */
      public com.the9.common.proto.Common.UserDTO.Builder getUserDTOBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getUserDTOFieldBuilder().getBuilder();
      }
      /**
       * <code>required .com.the9.common.proto.UserDTO userDTO = 1;</code>
       */
      public com.the9.common.proto.Common.UserDTOOrBuilder getUserDTOOrBuilder() {
        if (userDTOBuilder_ != null) {
          return userDTOBuilder_.getMessageOrBuilder();
        } else {
          return userDTO_;
        }
      }
      /**
       * <code>required .com.the9.common.proto.UserDTO userDTO = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.the9.common.proto.Common.UserDTO, com.the9.common.proto.Common.UserDTO.Builder, com.the9.common.proto.Common.UserDTOOrBuilder> 
          getUserDTOFieldBuilder() {
        if (userDTOBuilder_ == null) {
          userDTOBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.the9.common.proto.Common.UserDTO, com.the9.common.proto.Common.UserDTO.Builder, com.the9.common.proto.Common.UserDTOOrBuilder>(
                  userDTO_,
                  getParentForChildren(),
                  isClean());
          userDTO_ = null;
        }
        return userDTOBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.the9.common.proto.LoginGameAck)
    }

    static {
      defaultInstance = new LoginGameAck(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.the9.common.proto.LoginGameAck)
  }

  public interface LoginOutReqOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 userId = 1;
    /**
     * <code>required int32 userId = 1;</code>
     */
    boolean hasUserId();
    /**
     * <code>required int32 userId = 1;</code>
     */
    int getUserId();
  }
  /**
   * Protobuf type {@code com.the9.common.proto.LoginOutReq}
   */
  public static final class LoginOutReq extends
      com.google.protobuf.GeneratedMessage
      implements LoginOutReqOrBuilder {
    // Use LoginOutReq.newBuilder() to construct.
    private LoginOutReq(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private LoginOutReq(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final LoginOutReq defaultInstance;
    public static LoginOutReq getDefaultInstance() {
      return defaultInstance;
    }

    public LoginOutReq getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private LoginOutReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              userId_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.the9.common.proto.Rpc.internal_static_com_the9_common_proto_LoginOutReq_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.the9.common.proto.Rpc.internal_static_com_the9_common_proto_LoginOutReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.the9.common.proto.Rpc.LoginOutReq.class, com.the9.common.proto.Rpc.LoginOutReq.Builder.class);
    }

    public static com.google.protobuf.Parser<LoginOutReq> PARSER =
        new com.google.protobuf.AbstractParser<LoginOutReq>() {
      public LoginOutReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LoginOutReq(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<LoginOutReq> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 userId = 1;
    public static final int USERID_FIELD_NUMBER = 1;
    private int userId_;
    /**
     * <code>required int32 userId = 1;</code>
     */
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 userId = 1;</code>
     */
    public int getUserId() {
      return userId_;
    }

    private void initFields() {
      userId_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasUserId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, userId_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, userId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.the9.common.proto.Rpc.LoginOutReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.the9.common.proto.Rpc.LoginOutReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.the9.common.proto.Rpc.LoginOutReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.the9.common.proto.Rpc.LoginOutReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.the9.common.proto.Rpc.LoginOutReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.the9.common.proto.Rpc.LoginOutReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.the9.common.proto.Rpc.LoginOutReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.the9.common.proto.Rpc.LoginOutReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.the9.common.proto.Rpc.LoginOutReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.the9.common.proto.Rpc.LoginOutReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.the9.common.proto.Rpc.LoginOutReq prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.the9.common.proto.LoginOutReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.the9.common.proto.Rpc.LoginOutReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.the9.common.proto.Rpc.internal_static_com_the9_common_proto_LoginOutReq_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.the9.common.proto.Rpc.internal_static_com_the9_common_proto_LoginOutReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.the9.common.proto.Rpc.LoginOutReq.class, com.the9.common.proto.Rpc.LoginOutReq.Builder.class);
      }

      // Construct using com.the9.common.proto.Rpc.LoginOutReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        userId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.the9.common.proto.Rpc.internal_static_com_the9_common_proto_LoginOutReq_descriptor;
      }

      public com.the9.common.proto.Rpc.LoginOutReq getDefaultInstanceForType() {
        return com.the9.common.proto.Rpc.LoginOutReq.getDefaultInstance();
      }

      public com.the9.common.proto.Rpc.LoginOutReq build() {
        com.the9.common.proto.Rpc.LoginOutReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.the9.common.proto.Rpc.LoginOutReq buildPartial() {
        com.the9.common.proto.Rpc.LoginOutReq result = new com.the9.common.proto.Rpc.LoginOutReq(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.userId_ = userId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.the9.common.proto.Rpc.LoginOutReq) {
          return mergeFrom((com.the9.common.proto.Rpc.LoginOutReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.the9.common.proto.Rpc.LoginOutReq other) {
        if (other == com.the9.common.proto.Rpc.LoginOutReq.getDefaultInstance()) return this;
        if (other.hasUserId()) {
          setUserId(other.getUserId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUserId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.the9.common.proto.Rpc.LoginOutReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.the9.common.proto.Rpc.LoginOutReq) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 userId = 1;
      private int userId_ ;
      /**
       * <code>required int32 userId = 1;</code>
       */
      public boolean hasUserId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 userId = 1;</code>
       */
      public int getUserId() {
        return userId_;
      }
      /**
       * <code>required int32 userId = 1;</code>
       */
      public Builder setUserId(int value) {
        bitField0_ |= 0x00000001;
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 userId = 1;</code>
       */
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        userId_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.the9.common.proto.LoginOutReq)
    }

    static {
      defaultInstance = new LoginOutReq(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.the9.common.proto.LoginOutReq)
  }

  public interface GetServerConfigReqOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code com.the9.common.proto.GetServerConfigReq}
   */
  public static final class GetServerConfigReq extends
      com.google.protobuf.GeneratedMessage
      implements GetServerConfigReqOrBuilder {
    // Use GetServerConfigReq.newBuilder() to construct.
    private GetServerConfigReq(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private GetServerConfigReq(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final GetServerConfigReq defaultInstance;
    public static GetServerConfigReq getDefaultInstance() {
      return defaultInstance;
    }

    public GetServerConfigReq getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private GetServerConfigReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.the9.common.proto.Rpc.internal_static_com_the9_common_proto_GetServerConfigReq_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.the9.common.proto.Rpc.internal_static_com_the9_common_proto_GetServerConfigReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.the9.common.proto.Rpc.GetServerConfigReq.class, com.the9.common.proto.Rpc.GetServerConfigReq.Builder.class);
    }

    public static com.google.protobuf.Parser<GetServerConfigReq> PARSER =
        new com.google.protobuf.AbstractParser<GetServerConfigReq>() {
      public GetServerConfigReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GetServerConfigReq(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<GetServerConfigReq> getParserForType() {
      return PARSER;
    }

    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.the9.common.proto.Rpc.GetServerConfigReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.the9.common.proto.Rpc.GetServerConfigReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.the9.common.proto.Rpc.GetServerConfigReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.the9.common.proto.Rpc.GetServerConfigReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.the9.common.proto.Rpc.GetServerConfigReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.the9.common.proto.Rpc.GetServerConfigReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.the9.common.proto.Rpc.GetServerConfigReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.the9.common.proto.Rpc.GetServerConfigReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.the9.common.proto.Rpc.GetServerConfigReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.the9.common.proto.Rpc.GetServerConfigReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.the9.common.proto.Rpc.GetServerConfigReq prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.the9.common.proto.GetServerConfigReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.the9.common.proto.Rpc.GetServerConfigReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.the9.common.proto.Rpc.internal_static_com_the9_common_proto_GetServerConfigReq_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.the9.common.proto.Rpc.internal_static_com_the9_common_proto_GetServerConfigReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.the9.common.proto.Rpc.GetServerConfigReq.class, com.the9.common.proto.Rpc.GetServerConfigReq.Builder.class);
      }

      // Construct using com.the9.common.proto.Rpc.GetServerConfigReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.the9.common.proto.Rpc.internal_static_com_the9_common_proto_GetServerConfigReq_descriptor;
      }

      public com.the9.common.proto.Rpc.GetServerConfigReq getDefaultInstanceForType() {
        return com.the9.common.proto.Rpc.GetServerConfigReq.getDefaultInstance();
      }

      public com.the9.common.proto.Rpc.GetServerConfigReq build() {
        com.the9.common.proto.Rpc.GetServerConfigReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.the9.common.proto.Rpc.GetServerConfigReq buildPartial() {
        com.the9.common.proto.Rpc.GetServerConfigReq result = new com.the9.common.proto.Rpc.GetServerConfigReq(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.the9.common.proto.Rpc.GetServerConfigReq) {
          return mergeFrom((com.the9.common.proto.Rpc.GetServerConfigReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.the9.common.proto.Rpc.GetServerConfigReq other) {
        if (other == com.the9.common.proto.Rpc.GetServerConfigReq.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.the9.common.proto.Rpc.GetServerConfigReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.the9.common.proto.Rpc.GetServerConfigReq) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.the9.common.proto.GetServerConfigReq)
    }

    static {
      defaultInstance = new GetServerConfigReq(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.the9.common.proto.GetServerConfigReq)
  }

  public interface GetServerConfigAckOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .com.the9.common.proto.ServerConfigDTO cerverConfigDTO = 1;
    /**
     * <code>required .com.the9.common.proto.ServerConfigDTO cerverConfigDTO = 1;</code>
     */
    boolean hasCerverConfigDTO();
    /**
     * <code>required .com.the9.common.proto.ServerConfigDTO cerverConfigDTO = 1;</code>
     */
    com.the9.common.proto.Common.ServerConfigDTO getCerverConfigDTO();
    /**
     * <code>required .com.the9.common.proto.ServerConfigDTO cerverConfigDTO = 1;</code>
     */
    com.the9.common.proto.Common.ServerConfigDTOOrBuilder getCerverConfigDTOOrBuilder();
  }
  /**
   * Protobuf type {@code com.the9.common.proto.GetServerConfigAck}
   */
  public static final class GetServerConfigAck extends
      com.google.protobuf.GeneratedMessage
      implements GetServerConfigAckOrBuilder {
    // Use GetServerConfigAck.newBuilder() to construct.
    private GetServerConfigAck(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private GetServerConfigAck(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final GetServerConfigAck defaultInstance;
    public static GetServerConfigAck getDefaultInstance() {
      return defaultInstance;
    }

    public GetServerConfigAck getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private GetServerConfigAck(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.the9.common.proto.Common.ServerConfigDTO.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = cerverConfigDTO_.toBuilder();
              }
              cerverConfigDTO_ = input.readMessage(com.the9.common.proto.Common.ServerConfigDTO.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(cerverConfigDTO_);
                cerverConfigDTO_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.the9.common.proto.Rpc.internal_static_com_the9_common_proto_GetServerConfigAck_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.the9.common.proto.Rpc.internal_static_com_the9_common_proto_GetServerConfigAck_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.the9.common.proto.Rpc.GetServerConfigAck.class, com.the9.common.proto.Rpc.GetServerConfigAck.Builder.class);
    }

    public static com.google.protobuf.Parser<GetServerConfigAck> PARSER =
        new com.google.protobuf.AbstractParser<GetServerConfigAck>() {
      public GetServerConfigAck parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GetServerConfigAck(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<GetServerConfigAck> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required .com.the9.common.proto.ServerConfigDTO cerverConfigDTO = 1;
    public static final int CERVERCONFIGDTO_FIELD_NUMBER = 1;
    private com.the9.common.proto.Common.ServerConfigDTO cerverConfigDTO_;
    /**
     * <code>required .com.the9.common.proto.ServerConfigDTO cerverConfigDTO = 1;</code>
     */
    public boolean hasCerverConfigDTO() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .com.the9.common.proto.ServerConfigDTO cerverConfigDTO = 1;</code>
     */
    public com.the9.common.proto.Common.ServerConfigDTO getCerverConfigDTO() {
      return cerverConfigDTO_;
    }
    /**
     * <code>required .com.the9.common.proto.ServerConfigDTO cerverConfigDTO = 1;</code>
     */
    public com.the9.common.proto.Common.ServerConfigDTOOrBuilder getCerverConfigDTOOrBuilder() {
      return cerverConfigDTO_;
    }

    private void initFields() {
      cerverConfigDTO_ = com.the9.common.proto.Common.ServerConfigDTO.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasCerverConfigDTO()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, cerverConfigDTO_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, cerverConfigDTO_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.the9.common.proto.Rpc.GetServerConfigAck parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.the9.common.proto.Rpc.GetServerConfigAck parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.the9.common.proto.Rpc.GetServerConfigAck parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.the9.common.proto.Rpc.GetServerConfigAck parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.the9.common.proto.Rpc.GetServerConfigAck parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.the9.common.proto.Rpc.GetServerConfigAck parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.the9.common.proto.Rpc.GetServerConfigAck parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.the9.common.proto.Rpc.GetServerConfigAck parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.the9.common.proto.Rpc.GetServerConfigAck parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.the9.common.proto.Rpc.GetServerConfigAck parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.the9.common.proto.Rpc.GetServerConfigAck prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.the9.common.proto.GetServerConfigAck}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.the9.common.proto.Rpc.GetServerConfigAckOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.the9.common.proto.Rpc.internal_static_com_the9_common_proto_GetServerConfigAck_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.the9.common.proto.Rpc.internal_static_com_the9_common_proto_GetServerConfigAck_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.the9.common.proto.Rpc.GetServerConfigAck.class, com.the9.common.proto.Rpc.GetServerConfigAck.Builder.class);
      }

      // Construct using com.the9.common.proto.Rpc.GetServerConfigAck.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getCerverConfigDTOFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (cerverConfigDTOBuilder_ == null) {
          cerverConfigDTO_ = com.the9.common.proto.Common.ServerConfigDTO.getDefaultInstance();
        } else {
          cerverConfigDTOBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.the9.common.proto.Rpc.internal_static_com_the9_common_proto_GetServerConfigAck_descriptor;
      }

      public com.the9.common.proto.Rpc.GetServerConfigAck getDefaultInstanceForType() {
        return com.the9.common.proto.Rpc.GetServerConfigAck.getDefaultInstance();
      }

      public com.the9.common.proto.Rpc.GetServerConfigAck build() {
        com.the9.common.proto.Rpc.GetServerConfigAck result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.the9.common.proto.Rpc.GetServerConfigAck buildPartial() {
        com.the9.common.proto.Rpc.GetServerConfigAck result = new com.the9.common.proto.Rpc.GetServerConfigAck(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (cerverConfigDTOBuilder_ == null) {
          result.cerverConfigDTO_ = cerverConfigDTO_;
        } else {
          result.cerverConfigDTO_ = cerverConfigDTOBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.the9.common.proto.Rpc.GetServerConfigAck) {
          return mergeFrom((com.the9.common.proto.Rpc.GetServerConfigAck)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.the9.common.proto.Rpc.GetServerConfigAck other) {
        if (other == com.the9.common.proto.Rpc.GetServerConfigAck.getDefaultInstance()) return this;
        if (other.hasCerverConfigDTO()) {
          mergeCerverConfigDTO(other.getCerverConfigDTO());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasCerverConfigDTO()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.the9.common.proto.Rpc.GetServerConfigAck parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.the9.common.proto.Rpc.GetServerConfigAck) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .com.the9.common.proto.ServerConfigDTO cerverConfigDTO = 1;
      private com.the9.common.proto.Common.ServerConfigDTO cerverConfigDTO_ = com.the9.common.proto.Common.ServerConfigDTO.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.the9.common.proto.Common.ServerConfigDTO, com.the9.common.proto.Common.ServerConfigDTO.Builder, com.the9.common.proto.Common.ServerConfigDTOOrBuilder> cerverConfigDTOBuilder_;
      /**
       * <code>required .com.the9.common.proto.ServerConfigDTO cerverConfigDTO = 1;</code>
       */
      public boolean hasCerverConfigDTO() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .com.the9.common.proto.ServerConfigDTO cerverConfigDTO = 1;</code>
       */
      public com.the9.common.proto.Common.ServerConfigDTO getCerverConfigDTO() {
        if (cerverConfigDTOBuilder_ == null) {
          return cerverConfigDTO_;
        } else {
          return cerverConfigDTOBuilder_.getMessage();
        }
      }
      /**
       * <code>required .com.the9.common.proto.ServerConfigDTO cerverConfigDTO = 1;</code>
       */
      public Builder setCerverConfigDTO(com.the9.common.proto.Common.ServerConfigDTO value) {
        if (cerverConfigDTOBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          cerverConfigDTO_ = value;
          onChanged();
        } else {
          cerverConfigDTOBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .com.the9.common.proto.ServerConfigDTO cerverConfigDTO = 1;</code>
       */
      public Builder setCerverConfigDTO(
          com.the9.common.proto.Common.ServerConfigDTO.Builder builderForValue) {
        if (cerverConfigDTOBuilder_ == null) {
          cerverConfigDTO_ = builderForValue.build();
          onChanged();
        } else {
          cerverConfigDTOBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .com.the9.common.proto.ServerConfigDTO cerverConfigDTO = 1;</code>
       */
      public Builder mergeCerverConfigDTO(com.the9.common.proto.Common.ServerConfigDTO value) {
        if (cerverConfigDTOBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              cerverConfigDTO_ != com.the9.common.proto.Common.ServerConfigDTO.getDefaultInstance()) {
            cerverConfigDTO_ =
              com.the9.common.proto.Common.ServerConfigDTO.newBuilder(cerverConfigDTO_).mergeFrom(value).buildPartial();
          } else {
            cerverConfigDTO_ = value;
          }
          onChanged();
        } else {
          cerverConfigDTOBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .com.the9.common.proto.ServerConfigDTO cerverConfigDTO = 1;</code>
       */
      public Builder clearCerverConfigDTO() {
        if (cerverConfigDTOBuilder_ == null) {
          cerverConfigDTO_ = com.the9.common.proto.Common.ServerConfigDTO.getDefaultInstance();
          onChanged();
        } else {
          cerverConfigDTOBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>required .com.the9.common.proto.ServerConfigDTO cerverConfigDTO = 1;</code>
       */
      public com.the9.common.proto.Common.ServerConfigDTO.Builder getCerverConfigDTOBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getCerverConfigDTOFieldBuilder().getBuilder();
      }
      /**
       * <code>required .com.the9.common.proto.ServerConfigDTO cerverConfigDTO = 1;</code>
       */
      public com.the9.common.proto.Common.ServerConfigDTOOrBuilder getCerverConfigDTOOrBuilder() {
        if (cerverConfigDTOBuilder_ != null) {
          return cerverConfigDTOBuilder_.getMessageOrBuilder();
        } else {
          return cerverConfigDTO_;
        }
      }
      /**
       * <code>required .com.the9.common.proto.ServerConfigDTO cerverConfigDTO = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.the9.common.proto.Common.ServerConfigDTO, com.the9.common.proto.Common.ServerConfigDTO.Builder, com.the9.common.proto.Common.ServerConfigDTOOrBuilder> 
          getCerverConfigDTOFieldBuilder() {
        if (cerverConfigDTOBuilder_ == null) {
          cerverConfigDTOBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.the9.common.proto.Common.ServerConfigDTO, com.the9.common.proto.Common.ServerConfigDTO.Builder, com.the9.common.proto.Common.ServerConfigDTOOrBuilder>(
                  cerverConfigDTO_,
                  getParentForChildren(),
                  isClean());
          cerverConfigDTO_ = null;
        }
        return cerverConfigDTOBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.the9.common.proto.GetServerConfigAck)
    }

    static {
      defaultInstance = new GetServerConfigAck(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.the9.common.proto.GetServerConfigAck)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_the9_common_proto_LoginGameReq_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_the9_common_proto_LoginGameReq_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_the9_common_proto_LoginGameAck_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_the9_common_proto_LoginGameAck_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_the9_common_proto_LoginOutReq_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_the9_common_proto_LoginOutReq_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_the9_common_proto_GetServerConfigReq_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_the9_common_proto_GetServerConfigReq_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_the9_common_proto_GetServerConfigAck_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_the9_common_proto_GetServerConfigAck_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\trpc.proto\022\025com.the9.common.proto\032\014comm" +
      "on.proto\"\016\n\014LoginGameReq\"?\n\014LoginGameAck" +
      "\022/\n\007userDTO\030\001 \002(\0132\036.com.the9.common.prot" +
      "o.UserDTO\"\035\n\013LoginOutReq\022\016\n\006userId\030\001 \002(\005" +
      "\"\024\n\022GetServerConfigReq\"U\n\022GetServerConfi" +
      "gAck\022?\n\017cerverConfigDTO\030\001 \002(\0132&.com.the9" +
      ".common.proto.ServerConfigDTO"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_the9_common_proto_LoginGameReq_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_the9_common_proto_LoginGameReq_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_the9_common_proto_LoginGameReq_descriptor,
              new java.lang.String[] { });
          internal_static_com_the9_common_proto_LoginGameAck_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_the9_common_proto_LoginGameAck_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_the9_common_proto_LoginGameAck_descriptor,
              new java.lang.String[] { "UserDTO", });
          internal_static_com_the9_common_proto_LoginOutReq_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_com_the9_common_proto_LoginOutReq_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_the9_common_proto_LoginOutReq_descriptor,
              new java.lang.String[] { "UserId", });
          internal_static_com_the9_common_proto_GetServerConfigReq_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_com_the9_common_proto_GetServerConfigReq_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_the9_common_proto_GetServerConfigReq_descriptor,
              new java.lang.String[] { });
          internal_static_com_the9_common_proto_GetServerConfigAck_descriptor =
            getDescriptor().getMessageTypes().get(4);
          internal_static_com_the9_common_proto_GetServerConfigAck_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_the9_common_proto_GetServerConfigAck_descriptor,
              new java.lang.String[] { "CerverConfigDTO", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.the9.common.proto.Common.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
