// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: daisy.proto

package com.the9.daisy.network.proto;

public final class Daisy {
  private Daisy() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface GameMsgOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 type = 1;
    /**
     * <code>required int32 type = 1;</code>
     *
     * <pre>
     *消息类型值
     * </pre>
     */
    boolean hasType();
    /**
     * <code>required int32 type = 1;</code>
     *
     * <pre>
     *消息类型值
     * </pre>
     */
    int getType();

    // optional int32 flag = 2;
    /**
     * <code>optional int32 flag = 2;</code>
     *
     * <pre>
     *压缩加密标识
     * </pre>
     */
    boolean hasFlag();
    /**
     * <code>optional int32 flag = 2;</code>
     *
     * <pre>
     *压缩加密标识
     * </pre>
     */
    int getFlag();

    // required bytes content = 3;
    /**
     * <code>required bytes content = 3;</code>
     *
     * <pre>
     *内容
     * </pre>
     */
    boolean hasContent();
    /**
     * <code>required bytes content = 3;</code>
     *
     * <pre>
     *内容
     * </pre>
     */
    com.google.protobuf.ByteString getContent();

    // optional int64 timestamp = 4;
    /**
     * <code>optional int64 timestamp = 4;</code>
     *
     * <pre>
     *时间戳，客户端模拟的服务器时间
     * </pre>
     */
    boolean hasTimestamp();
    /**
     * <code>optional int64 timestamp = 4;</code>
     *
     * <pre>
     *时间戳，客户端模拟的服务器时间
     * </pre>
     */
    long getTimestamp();

    // optional int32 id = 5;
    /**
     * <code>optional int32 id = 5;</code>
     *
     * <pre>
     *消息id，由客户端生成
     * </pre>
     */
    boolean hasId();
    /**
     * <code>optional int32 id = 5;</code>
     *
     * <pre>
     *消息id，由客户端生成
     * </pre>
     */
    int getId();
  }
  /**
   * Protobuf type {@code com.the9.daisy.network.proto.GameMsg}
   *
   * <pre>
   *与客户端通信的消息
   * </pre>
   */
  public static final class GameMsg extends
      com.google.protobuf.GeneratedMessage
      implements GameMsgOrBuilder {
    // Use GameMsg.newBuilder() to construct.
    private GameMsg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private GameMsg(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final GameMsg defaultInstance;
    public static GameMsg getDefaultInstance() {
      return defaultInstance;
    }

    public GameMsg getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private GameMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              type_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              flag_ = input.readInt32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              content_ = input.readBytes();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              timestamp_ = input.readInt64();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              id_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.the9.daisy.network.proto.Daisy.internal_static_com_the9_daisy_network_proto_GameMsg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.the9.daisy.network.proto.Daisy.internal_static_com_the9_daisy_network_proto_GameMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.the9.daisy.network.proto.Daisy.GameMsg.class, com.the9.daisy.network.proto.Daisy.GameMsg.Builder.class);
    }

    public static com.google.protobuf.Parser<GameMsg> PARSER =
        new com.google.protobuf.AbstractParser<GameMsg>() {
      public GameMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GameMsg(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<GameMsg> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>required int32 type = 1;</code>
     *
     * <pre>
     *消息类型值
     * </pre>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 type = 1;</code>
     *
     * <pre>
     *消息类型值
     * </pre>
     */
    public int getType() {
      return type_;
    }

    // optional int32 flag = 2;
    public static final int FLAG_FIELD_NUMBER = 2;
    private int flag_;
    /**
     * <code>optional int32 flag = 2;</code>
     *
     * <pre>
     *压缩加密标识
     * </pre>
     */
    public boolean hasFlag() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 flag = 2;</code>
     *
     * <pre>
     *压缩加密标识
     * </pre>
     */
    public int getFlag() {
      return flag_;
    }

    // required bytes content = 3;
    public static final int CONTENT_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString content_;
    /**
     * <code>required bytes content = 3;</code>
     *
     * <pre>
     *内容
     * </pre>
     */
    public boolean hasContent() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required bytes content = 3;</code>
     *
     * <pre>
     *内容
     * </pre>
     */
    public com.google.protobuf.ByteString getContent() {
      return content_;
    }

    // optional int64 timestamp = 4;
    public static final int TIMESTAMP_FIELD_NUMBER = 4;
    private long timestamp_;
    /**
     * <code>optional int64 timestamp = 4;</code>
     *
     * <pre>
     *时间戳，客户端模拟的服务器时间
     * </pre>
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int64 timestamp = 4;</code>
     *
     * <pre>
     *时间戳，客户端模拟的服务器时间
     * </pre>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    // optional int32 id = 5;
    public static final int ID_FIELD_NUMBER = 5;
    private int id_;
    /**
     * <code>optional int32 id = 5;</code>
     *
     * <pre>
     *消息id，由客户端生成
     * </pre>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int32 id = 5;</code>
     *
     * <pre>
     *消息id，由客户端生成
     * </pre>
     */
    public int getId() {
      return id_;
    }

    private void initFields() {
      type_ = 0;
      flag_ = 0;
      content_ = com.google.protobuf.ByteString.EMPTY;
      timestamp_ = 0L;
      id_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasContent()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, type_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, flag_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, content_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt64(4, timestamp_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, id_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, type_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, flag_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, content_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, timestamp_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, id_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.the9.daisy.network.proto.Daisy.GameMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.the9.daisy.network.proto.Daisy.GameMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.the9.daisy.network.proto.Daisy.GameMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.the9.daisy.network.proto.Daisy.GameMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.the9.daisy.network.proto.Daisy.GameMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.the9.daisy.network.proto.Daisy.GameMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.the9.daisy.network.proto.Daisy.GameMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.the9.daisy.network.proto.Daisy.GameMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.the9.daisy.network.proto.Daisy.GameMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.the9.daisy.network.proto.Daisy.GameMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.the9.daisy.network.proto.Daisy.GameMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.the9.daisy.network.proto.GameMsg}
     *
     * <pre>
     *与客户端通信的消息
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.the9.daisy.network.proto.Daisy.GameMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.the9.daisy.network.proto.Daisy.internal_static_com_the9_daisy_network_proto_GameMsg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.the9.daisy.network.proto.Daisy.internal_static_com_the9_daisy_network_proto_GameMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.the9.daisy.network.proto.Daisy.GameMsg.class, com.the9.daisy.network.proto.Daisy.GameMsg.Builder.class);
      }

      // Construct using com.the9.daisy.network.proto.Daisy.GameMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        flag_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        content_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        timestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.the9.daisy.network.proto.Daisy.internal_static_com_the9_daisy_network_proto_GameMsg_descriptor;
      }

      public com.the9.daisy.network.proto.Daisy.GameMsg getDefaultInstanceForType() {
        return com.the9.daisy.network.proto.Daisy.GameMsg.getDefaultInstance();
      }

      public com.the9.daisy.network.proto.Daisy.GameMsg build() {
        com.the9.daisy.network.proto.Daisy.GameMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.the9.daisy.network.proto.Daisy.GameMsg buildPartial() {
        com.the9.daisy.network.proto.Daisy.GameMsg result = new com.the9.daisy.network.proto.Daisy.GameMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.flag_ = flag_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.content_ = content_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.timestamp_ = timestamp_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.id_ = id_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.the9.daisy.network.proto.Daisy.GameMsg) {
          return mergeFrom((com.the9.daisy.network.proto.Daisy.GameMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.the9.daisy.network.proto.Daisy.GameMsg other) {
        if (other == com.the9.daisy.network.proto.Daisy.GameMsg.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasFlag()) {
          setFlag(other.getFlag());
        }
        if (other.hasContent()) {
          setContent(other.getContent());
        }
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        if (other.hasId()) {
          setId(other.getId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        if (!hasContent()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.the9.daisy.network.proto.Daisy.GameMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.the9.daisy.network.proto.Daisy.GameMsg) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 type = 1;
      private int type_ ;
      /**
       * <code>required int32 type = 1;</code>
       *
       * <pre>
       *消息类型值
       * </pre>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 type = 1;</code>
       *
       * <pre>
       *消息类型值
       * </pre>
       */
      public int getType() {
        return type_;
      }
      /**
       * <code>required int32 type = 1;</code>
       *
       * <pre>
       *消息类型值
       * </pre>
       */
      public Builder setType(int value) {
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 type = 1;</code>
       *
       * <pre>
       *消息类型值
       * </pre>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = 0;
        onChanged();
        return this;
      }

      // optional int32 flag = 2;
      private int flag_ ;
      /**
       * <code>optional int32 flag = 2;</code>
       *
       * <pre>
       *压缩加密标识
       * </pre>
       */
      public boolean hasFlag() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 flag = 2;</code>
       *
       * <pre>
       *压缩加密标识
       * </pre>
       */
      public int getFlag() {
        return flag_;
      }
      /**
       * <code>optional int32 flag = 2;</code>
       *
       * <pre>
       *压缩加密标识
       * </pre>
       */
      public Builder setFlag(int value) {
        bitField0_ |= 0x00000002;
        flag_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 flag = 2;</code>
       *
       * <pre>
       *压缩加密标识
       * </pre>
       */
      public Builder clearFlag() {
        bitField0_ = (bitField0_ & ~0x00000002);
        flag_ = 0;
        onChanged();
        return this;
      }

      // required bytes content = 3;
      private com.google.protobuf.ByteString content_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes content = 3;</code>
       *
       * <pre>
       *内容
       * </pre>
       */
      public boolean hasContent() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required bytes content = 3;</code>
       *
       * <pre>
       *内容
       * </pre>
       */
      public com.google.protobuf.ByteString getContent() {
        return content_;
      }
      /**
       * <code>required bytes content = 3;</code>
       *
       * <pre>
       *内容
       * </pre>
       */
      public Builder setContent(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes content = 3;</code>
       *
       * <pre>
       *内容
       * </pre>
       */
      public Builder clearContent() {
        bitField0_ = (bitField0_ & ~0x00000004);
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }

      // optional int64 timestamp = 4;
      private long timestamp_ ;
      /**
       * <code>optional int64 timestamp = 4;</code>
       *
       * <pre>
       *时间戳，客户端模拟的服务器时间
       * </pre>
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int64 timestamp = 4;</code>
       *
       * <pre>
       *时间戳，客户端模拟的服务器时间
       * </pre>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>optional int64 timestamp = 4;</code>
       *
       * <pre>
       *时间戳，客户端模拟的服务器时间
       * </pre>
       */
      public Builder setTimestamp(long value) {
        bitField0_ |= 0x00000008;
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 timestamp = 4;</code>
       *
       * <pre>
       *时间戳，客户端模拟的服务器时间
       * </pre>
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000008);
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      // optional int32 id = 5;
      private int id_ ;
      /**
       * <code>optional int32 id = 5;</code>
       *
       * <pre>
       *消息id，由客户端生成
       * </pre>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int32 id = 5;</code>
       *
       * <pre>
       *消息id，由客户端生成
       * </pre>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>optional int32 id = 5;</code>
       *
       * <pre>
       *消息id，由客户端生成
       * </pre>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000010;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 id = 5;</code>
       *
       * <pre>
       *消息id，由客户端生成
       * </pre>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000010);
        id_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.the9.daisy.network.proto.GameMsg)
    }

    static {
      defaultInstance = new GameMsg(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.the9.daisy.network.proto.GameMsg)
  }

  public interface RpcMsgOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 seqId = 1;
    /**
     * <code>required int32 seqId = 1;</code>
     *
     * <pre>
     *消息流水id，用于确定rpc源消息与rpc回调消息的时候相对应
     * </pre>
     */
    boolean hasSeqId();
    /**
     * <code>required int32 seqId = 1;</code>
     *
     * <pre>
     *消息流水id，用于确定rpc源消息与rpc回调消息的时候相对应
     * </pre>
     */
    int getSeqId();

    // optional int64 timestamp = 2;
    /**
     * <code>optional int64 timestamp = 2;</code>
     *
     * <pre>
     *时间戳
     * </pre>
     */
    boolean hasTimestamp();
    /**
     * <code>optional int64 timestamp = 2;</code>
     *
     * <pre>
     *时间戳
     * </pre>
     */
    long getTimestamp();

    // required int32 type = 3;
    /**
     * <code>required int32 type = 3;</code>
     *
     * <pre>
     *消息类型值
     * </pre>
     */
    boolean hasType();
    /**
     * <code>required int32 type = 3;</code>
     *
     * <pre>
     *消息类型值
     * </pre>
     */
    int getType();

    // required bytes content = 4;
    /**
     * <code>required bytes content = 4;</code>
     *
     * <pre>
     *这里的content就是我们自定义的消息
     * </pre>
     */
    boolean hasContent();
    /**
     * <code>required bytes content = 4;</code>
     *
     * <pre>
     *这里的content就是我们自定义的消息
     * </pre>
     */
    com.google.protobuf.ByteString getContent();
  }
  /**
   * Protobuf type {@code com.the9.daisy.network.proto.RpcMsg}
   *
   * <pre>
   *rpc通信的基本消息
   * </pre>
   */
  public static final class RpcMsg extends
      com.google.protobuf.GeneratedMessage
      implements RpcMsgOrBuilder {
    // Use RpcMsg.newBuilder() to construct.
    private RpcMsg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RpcMsg(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RpcMsg defaultInstance;
    public static RpcMsg getDefaultInstance() {
      return defaultInstance;
    }

    public RpcMsg getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RpcMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              seqId_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              timestamp_ = input.readInt64();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              type_ = input.readInt32();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              content_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.the9.daisy.network.proto.Daisy.internal_static_com_the9_daisy_network_proto_RpcMsg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.the9.daisy.network.proto.Daisy.internal_static_com_the9_daisy_network_proto_RpcMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.the9.daisy.network.proto.Daisy.RpcMsg.class, com.the9.daisy.network.proto.Daisy.RpcMsg.Builder.class);
    }

    public static com.google.protobuf.Parser<RpcMsg> PARSER =
        new com.google.protobuf.AbstractParser<RpcMsg>() {
      public RpcMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RpcMsg(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RpcMsg> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 seqId = 1;
    public static final int SEQID_FIELD_NUMBER = 1;
    private int seqId_;
    /**
     * <code>required int32 seqId = 1;</code>
     *
     * <pre>
     *消息流水id，用于确定rpc源消息与rpc回调消息的时候相对应
     * </pre>
     */
    public boolean hasSeqId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 seqId = 1;</code>
     *
     * <pre>
     *消息流水id，用于确定rpc源消息与rpc回调消息的时候相对应
     * </pre>
     */
    public int getSeqId() {
      return seqId_;
    }

    // optional int64 timestamp = 2;
    public static final int TIMESTAMP_FIELD_NUMBER = 2;
    private long timestamp_;
    /**
     * <code>optional int64 timestamp = 2;</code>
     *
     * <pre>
     *时间戳
     * </pre>
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int64 timestamp = 2;</code>
     *
     * <pre>
     *时间戳
     * </pre>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    // required int32 type = 3;
    public static final int TYPE_FIELD_NUMBER = 3;
    private int type_;
    /**
     * <code>required int32 type = 3;</code>
     *
     * <pre>
     *消息类型值
     * </pre>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 type = 3;</code>
     *
     * <pre>
     *消息类型值
     * </pre>
     */
    public int getType() {
      return type_;
    }

    // required bytes content = 4;
    public static final int CONTENT_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString content_;
    /**
     * <code>required bytes content = 4;</code>
     *
     * <pre>
     *这里的content就是我们自定义的消息
     * </pre>
     */
    public boolean hasContent() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required bytes content = 4;</code>
     *
     * <pre>
     *这里的content就是我们自定义的消息
     * </pre>
     */
    public com.google.protobuf.ByteString getContent() {
      return content_;
    }

    private void initFields() {
      seqId_ = 0;
      timestamp_ = 0L;
      type_ = 0;
      content_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasSeqId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasContent()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, seqId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, timestamp_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, type_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, content_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, seqId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, timestamp_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, type_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, content_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.the9.daisy.network.proto.Daisy.RpcMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.the9.daisy.network.proto.Daisy.RpcMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.the9.daisy.network.proto.Daisy.RpcMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.the9.daisy.network.proto.Daisy.RpcMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.the9.daisy.network.proto.Daisy.RpcMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.the9.daisy.network.proto.Daisy.RpcMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.the9.daisy.network.proto.Daisy.RpcMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.the9.daisy.network.proto.Daisy.RpcMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.the9.daisy.network.proto.Daisy.RpcMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.the9.daisy.network.proto.Daisy.RpcMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.the9.daisy.network.proto.Daisy.RpcMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.the9.daisy.network.proto.RpcMsg}
     *
     * <pre>
     *rpc通信的基本消息
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.the9.daisy.network.proto.Daisy.RpcMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.the9.daisy.network.proto.Daisy.internal_static_com_the9_daisy_network_proto_RpcMsg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.the9.daisy.network.proto.Daisy.internal_static_com_the9_daisy_network_proto_RpcMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.the9.daisy.network.proto.Daisy.RpcMsg.class, com.the9.daisy.network.proto.Daisy.RpcMsg.Builder.class);
      }

      // Construct using com.the9.daisy.network.proto.Daisy.RpcMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        seqId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        timestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        content_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.the9.daisy.network.proto.Daisy.internal_static_com_the9_daisy_network_proto_RpcMsg_descriptor;
      }

      public com.the9.daisy.network.proto.Daisy.RpcMsg getDefaultInstanceForType() {
        return com.the9.daisy.network.proto.Daisy.RpcMsg.getDefaultInstance();
      }

      public com.the9.daisy.network.proto.Daisy.RpcMsg build() {
        com.the9.daisy.network.proto.Daisy.RpcMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.the9.daisy.network.proto.Daisy.RpcMsg buildPartial() {
        com.the9.daisy.network.proto.Daisy.RpcMsg result = new com.the9.daisy.network.proto.Daisy.RpcMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.seqId_ = seqId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.timestamp_ = timestamp_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.content_ = content_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.the9.daisy.network.proto.Daisy.RpcMsg) {
          return mergeFrom((com.the9.daisy.network.proto.Daisy.RpcMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.the9.daisy.network.proto.Daisy.RpcMsg other) {
        if (other == com.the9.daisy.network.proto.Daisy.RpcMsg.getDefaultInstance()) return this;
        if (other.hasSeqId()) {
          setSeqId(other.getSeqId());
        }
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasContent()) {
          setContent(other.getContent());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasSeqId()) {
          
          return false;
        }
        if (!hasType()) {
          
          return false;
        }
        if (!hasContent()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.the9.daisy.network.proto.Daisy.RpcMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.the9.daisy.network.proto.Daisy.RpcMsg) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 seqId = 1;
      private int seqId_ ;
      /**
       * <code>required int32 seqId = 1;</code>
       *
       * <pre>
       *消息流水id，用于确定rpc源消息与rpc回调消息的时候相对应
       * </pre>
       */
      public boolean hasSeqId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 seqId = 1;</code>
       *
       * <pre>
       *消息流水id，用于确定rpc源消息与rpc回调消息的时候相对应
       * </pre>
       */
      public int getSeqId() {
        return seqId_;
      }
      /**
       * <code>required int32 seqId = 1;</code>
       *
       * <pre>
       *消息流水id，用于确定rpc源消息与rpc回调消息的时候相对应
       * </pre>
       */
      public Builder setSeqId(int value) {
        bitField0_ |= 0x00000001;
        seqId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 seqId = 1;</code>
       *
       * <pre>
       *消息流水id，用于确定rpc源消息与rpc回调消息的时候相对应
       * </pre>
       */
      public Builder clearSeqId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        seqId_ = 0;
        onChanged();
        return this;
      }

      // optional int64 timestamp = 2;
      private long timestamp_ ;
      /**
       * <code>optional int64 timestamp = 2;</code>
       *
       * <pre>
       *时间戳
       * </pre>
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int64 timestamp = 2;</code>
       *
       * <pre>
       *时间戳
       * </pre>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>optional int64 timestamp = 2;</code>
       *
       * <pre>
       *时间戳
       * </pre>
       */
      public Builder setTimestamp(long value) {
        bitField0_ |= 0x00000002;
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 timestamp = 2;</code>
       *
       * <pre>
       *时间戳
       * </pre>
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000002);
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      // required int32 type = 3;
      private int type_ ;
      /**
       * <code>required int32 type = 3;</code>
       *
       * <pre>
       *消息类型值
       * </pre>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 type = 3;</code>
       *
       * <pre>
       *消息类型值
       * </pre>
       */
      public int getType() {
        return type_;
      }
      /**
       * <code>required int32 type = 3;</code>
       *
       * <pre>
       *消息类型值
       * </pre>
       */
      public Builder setType(int value) {
        bitField0_ |= 0x00000004;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 type = 3;</code>
       *
       * <pre>
       *消息类型值
       * </pre>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        type_ = 0;
        onChanged();
        return this;
      }

      // required bytes content = 4;
      private com.google.protobuf.ByteString content_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes content = 4;</code>
       *
       * <pre>
       *这里的content就是我们自定义的消息
       * </pre>
       */
      public boolean hasContent() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required bytes content = 4;</code>
       *
       * <pre>
       *这里的content就是我们自定义的消息
       * </pre>
       */
      public com.google.protobuf.ByteString getContent() {
        return content_;
      }
      /**
       * <code>required bytes content = 4;</code>
       *
       * <pre>
       *这里的content就是我们自定义的消息
       * </pre>
       */
      public Builder setContent(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes content = 4;</code>
       *
       * <pre>
       *这里的content就是我们自定义的消息
       * </pre>
       */
      public Builder clearContent() {
        bitField0_ = (bitField0_ & ~0x00000008);
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.the9.daisy.network.proto.RpcMsg)
    }

    static {
      defaultInstance = new RpcMsg(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.the9.daisy.network.proto.RpcMsg)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_the9_daisy_network_proto_GameMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_the9_daisy_network_proto_GameMsg_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_the9_daisy_network_proto_RpcMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_the9_daisy_network_proto_RpcMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013daisy.proto\022\034com.the9.daisy.network.pr" +
      "oto\"U\n\007GameMsg\022\014\n\004type\030\001 \002(\005\022\014\n\004flag\030\002 \001" +
      "(\005\022\017\n\007content\030\003 \002(\014\022\021\n\ttimestamp\030\004 \001(\003\022\n" +
      "\n\002id\030\005 \001(\005\"I\n\006RpcMsg\022\r\n\005seqId\030\001 \002(\005\022\021\n\tt" +
      "imestamp\030\002 \001(\003\022\014\n\004type\030\003 \002(\005\022\017\n\007content\030" +
      "\004 \002(\014"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_the9_daisy_network_proto_GameMsg_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_the9_daisy_network_proto_GameMsg_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_the9_daisy_network_proto_GameMsg_descriptor,
              new java.lang.String[] { "Type", "Flag", "Content", "Timestamp", "Id", });
          internal_static_com_the9_daisy_network_proto_RpcMsg_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_the9_daisy_network_proto_RpcMsg_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_the9_daisy_network_proto_RpcMsg_descriptor,
              new java.lang.String[] { "SeqId", "Timestamp", "Type", "Content", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
